spring:
  profiles:
    active: 
    - dev
    
---
spring:
  profiles: dev
  application:
    name: springCloudConfig-dev
    
---
spring:
  profiles: test
  application:
    name: springCloudConfig-test