spring:
  profiles:
    active: 
    - dev
    
---
spring:
  profiles: dev
  application:
    name: springCloudConfig-dev
config:
  info: 'I am dev 4'
    
---
spring:
  profiles: test
  application:
    name: springCloudConfig-test

config:
  info: 'I am test 4'
